# Generated by Django 5.2.4 on 2025-07-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(null=True, upload_to='movies_images'),
        ),
    ]
